### ISSUE TITLE
Are there any plans on the Maven support?

### ISSUE THREAD

**Issue by volodymyrrudyi** [peterdmv/treemap#1]
Hello!

Thanks a lot for the repository. [This project](https://github.com/lwaddicor/spring-startup-analysis) is using the code from here. Since there is no Maven packaging (pom.xml), they have to copy/paste it.

Are you planning to add the pom.xml to this repo?

**Comment by peterdmv** [comment]
Hi,
Nice to hear that someone is using my code. I didn't have any plan to add maven support but I will consider it. I think in your case even a git submodule would work.

**Comment by volodymyrrudyi** [comment]
Yeah, but it's not so fancy and flexible as the Maven artifact :)   Thanks for your response, please let me know if you need some assistance with the Maven support, I could create a PR with the pom.xml

**Comment by peterdmv** [comment]
It would definitely help if you could create a PR with a pom.xml.
